### ISSUE TITLE
trim_osc.py "ways that are not in the bounding box but are in the database" processing fails with diffs from yesterday

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Zverik/regional#15]
Here's the error in the log:

[2021-05-31 13:46:09] 27935 Done with import
[2021-05-31 13:50:01] 28938 start import from seq-nr 4564062, replag is 18 hour(s)
[2021-05-31 13:50:01] 28938 downloading diff
[2021-05-31 13:52:22] 28938 filtering diff
Traceback (most recent call last):
  File "/home/renderaccount/src/regional/trim_osc.py", line 154, in <module>
    for nd in root.xpath('//way[@id={}]/nd'.format(row[0])):
  File "src/lxml/etree.pyx", line 1577, in lxml.etree._Element.xpath
  File "src/lxml/xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__
  File "src/lxml/xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result
lxml.etree.XPathEvalError: Invalid expression
[2021-05-31 13:52:38] 28938 [error] Trim_osc error
[2021-05-31 13:52:38] 28938 resetting state

I saved the offending file at https://map.atownsend.org.uk/tmp/changes.osc_save.gz (21Mb).
I can't see any obvious problems why it would cause a problem - xmllint seems happy with it (it only changes quotes), and there are no oddities in the file like modified ways with zero nodes.

It's just diffs from this one time (seen on two different machines with very different database contents) - later or earlier diffs do not have a problem.

**Comment by SomeoneElseOSM** [comment]
Actually - the code I was using was older than I thought it was.  Let me check the current version first!

**Comment by Zverik** [comment]
Can `row[0]` be empty? Not sure where to look at the code, since that's not what inside this repo.

**Comment by Zverik** [comment]
Indeed, looks like #6.
