### ISSUE TITLE
Problem with python-lxml

### ISSUE THREAD

**Issue by lakul** [Zverik/regional#2]
During the import, I get the following error:

```
[2014-11-14 11:30:57] 14425 filtering diff
Traceback (most recent call last):
  File "/tmp/trim_osc.py", line 131, in <module>
    for nd in root.xpath('//way[@id={}]/nd'.format(row[0])):
  File "lxml.etree.pyx", line 1509, in lxml.etree._Element.xpath (src/lxml/lxml.
  File "xpath.pxi", line 318, in lxml.etree.XPathElementEvaluator.__call__ (src/                                                                                                                     .c:145954)
  File "xpath.pxi", line 238, in lxml.etree._XPathEvaluatorBase._handle_result (                                                                                                                     tree.c:144962)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_erro                                                                                                                     l.etree.c:144817)
```

I installed "python-lxml 3.3.3", but on another computer it works with this version.  I always work with the same region "Germany".

Many thanks!
Christian

**Comment by Zverik** [comment]
Most likely this was a broken lxml or out of memory error.
