### ISSUE TITLE
AttributeError: 'list' object has no attribute '__array_interface__'

### ISSUE THREAD

**Issue by Peuc** [Zverik/regional#5]
When trying to run `trim_osc.py`, I get the following error:
```
$ ./trim_osc.py -p canada.poly changes.osc changes-canada.osc
Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./trim_osc.py", line 82, in <module>
    tpoly = poly_parse(options.poly)
  File "./trim_osc.py", line 42, in poly_parse
    result = Polygon(poly)
  File "/usr/lib/python3/dist-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/usr/lib/python3/dist-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 319, in shapely.speedups._speedups.geos_linearring_from_py
TypeError: object of type 'map' has no len()
```
Looks like the problem occurs while parsing [this poly file](http://download.geofabrik.de/north-america/canada.poly). Shapely comes from the latest Ubuntu 18.04 packages.

Any clue?

**Comment by SosthenG** [comment]
Looks like it's related to python3.
Executing the script with python (instead of python3) worked for me.

**Comment by amenk** [comment]
@SosthenG Having the same error ... which python version are you using to get it work? (`python -v`)

**Comment by Zverik** [comment]
#8 should have fixed that.
