### ISSUE TITLE
Correct scripts prerequisites

### ISSUE THREAD

**Issue by YuriiNskyi** [Zverik/regional#9]
Working environment is `Ubuntu 18.04 LTS`

According to [this guide](https://ircama.github.io/osm-carto-tutorials/updating-data/), I'm trying to trim my downloaded OSM changes.

After executing `sudo apt-get install -y python-psycopg2 python-shapely python-lxml`, there were problems with versions of these libraries, which are solved by these commands:

```
sudo apt-get install python3-psycopg2
sudo apt-get -y install python3-pip
pip3 install lxml
pip3 install shapely
```

Now, executing the script `~/src/regional/trim_osc.py -d gis --user postgres --host localhost --port 5432 --password -p "${WORKOSM_DIR}/andorra.poly" osmChange osmChangeTrimmed`, we have this error:

>Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rosm/src/regional/trim_osc.py", line 82, in <module>
    tpoly = poly_parse(options.poly)
  File "/home/rosm/src/regional/trim_osc.py", line 42, in poly_parse
    result = Polygon(poly)
  File "/home/rosm/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/home/rosm/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 319, in shapely.speedups._speedups.geos_linearring_from_py
TypeError: object of type 'map' has no len()

How can I solve this? Maybe prerequisites for executing this script should be provided, because not all the users who want it are professional Python developers.

**Comment by Zverik** [comment]
Try redownloading the script and trying again: #8 should have fixed that.
